/*
 * Java domain class for entity "Employee" 
 * Created on 2024-04-22 ( Date ISO 2024-04-22 - Time 21:42:03 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.hoa.repositories;

import com.hoa.entities.Employee;
import com.hoa.responseEntities.EmployeeResponseWithIdAndName;

import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

/**
 * <h2>EmployeeRepository</h2>
 *
 * createdAt : 2024-04-22 - Time 21:42:03
 * <p>
 * Description: Spring Data repository for the {@link Employee} entity.
 * 
 * @author aek
 */
@Repository
public interface EmployeeRepository extends JpaRepository<Employee, Integer>, JpaSpecificationExecutor<Employee> {

	Employee findEmployeeByUserId(Integer userId);

	@Query("Select COUNT(e) from Employee e where e.employeeNo= :employeeNo")
	int countByEmployeeNo(String employeeNo);

	@Query(value = "SELECT \n" + 
	"	e.employee_id AS employeeId,\n" + 
	"	u.first_name AS firstName\n" + 
	"FROM \n"
			+ "	employee e\n" + 
	"JOIN\n" +
			"	\"user\" u ON e.user_id = u.user_id\n" +
	"WHERE\n"
			+ "	e.designation_id = :designationId", nativeQuery = true)
	List<Map<String, Object>> getEmployeeResponseWithIdAndName(@Param("designationId") Integer designationId);

	@Query(value = "SELECT \n" + 
	"    e.employee_id AS employeeId, \n" + 
			"    u.first_name AS firstName \n" + 
	"FROM \n"
			+ "    employee e \n" +
	"JOIN \n" + "    \"user\" u ON e.user_id = u.user_id \n" +
	"WHERE \n"
			+ "    e.manager_id = :managerId", nativeQuery = true)
	List<Map<String, Object>> getEmployeeResponseWithIdAndNameByManagerId(@Param("managerId") Integer managerId);

}
