spring:
  application:
    name: HOA
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true     
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Uye39%2wlrLp
    url: jdbc:postgresql://vhoasdb.c1muummy818d.us-east-1.rds.amazonaws.com:5432/Initialvhoasdb
  
  main:
    allow-circular-references: true 
    
  mail:
    host: smtp.gmail.com        # SMTP server host
    port: 587                     # Port number (587 for TLS, 465 for SSL)
    username: arunachalamselvam6599@gmail.com       # SMTP username
    password: qbff igpu dtqk mmua       # SMTP password
    properties:
      mail:
        smtp:
          auth: true               # Enable authentication
          starttls:
            enable: true           # Enable STARTTLS encryption
          ssl:
            trust: '*'  
     
server:
  port: 80 # Change this to your desired port number
  servlet : 
    context-path : /hoa
    
    
  
