spring:
  application:
    name: HOA
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true     
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: Arun@1103
    url: jdbc:postgresql://localhost:5432/HOA_Project
   
     
server:
  port: 8081 # Change this to your desired port number
  servlet : 
    context-path : /hoa
  
